name: pay_example
description: Demonstrates how to use the pay plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
publish_to: 'none'

environment:
  sdk: ^2.7.0
  flutter: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  pay:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
   sdk: flutter
  integration_test: ^0.9.2
