name: pay_example
description: Demonstrates how to use the pay plugin.
author: Flutter Team <flutter-dev@googlegroups.com>
publish_to: 'none'

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  pay:
    path: ../

  stripe_platform_interface:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: stripe_platform_interface

  stripe:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: stripe

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dependency_overrides:
  stripe_platform_interface:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      path: stripe_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
   sdk: flutter
  integration_test:
   sdk: flutter
