name: pay_mobile
description: A plug-in to add support for payment wallets on Flutter applications.
version: 1.0.0-beta.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: TBA

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.pay_mobile
        pluginClass: PayPlugin
      ios:
        pluginClass: PayPlugin

  assets:
    - assets/

dependencies:
  flutter:
    sdk: flutter
  #pay_platform_interface: ^1.0.0
  pay_platform_interface:
    path: ../pay_platform_interface
  flutter_svg: 0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.6