name: pay
description: A plug-in to add support for payment wallets on Flutter applications.
version: 1.0.0
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: TBA

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  #pay_android: ^1.0.0
  pay_android:
    path: ../pay_android
  #pay_ios: ^1.0.0
  pay_ios:
    path: ../pay_ios
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.11.0
  test: ^1.15.6