name: google_pay
description: A plug-in to add support for Google Pay on Flutter applications.
version: 1.0.0
author: Google Pay Team <payments-devrel@googlegroups.com>
homepage: https://developers.google.com/pay/api/android/overview

environment:
  sdk: ^2.7.0
  flutter: ^1.20.0

dependencies:
  flutter:
    sdk: flutter
  #google_pay_mobile: ^1.0.0
  google_pay_mobile:
    path: ../google_pay_mobile
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
   sdk: flutter
  e2e: ^0.2.1
  mockito: ^4.1.3
  test: ^1.15.6