name: pay_platform_interface
description: A common platform interface for payment plugins for Flutter.
version: 1.0.0
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: TBA

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

flutter:
  assets:
    - pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
