name: google_pay_example
description: Demonstrates how to use the google_pay plugin.
publish_to: 'none'

environment:
  sdk: ^2.7.0
  flutter: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_payment_profile.json
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  google_pay:
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
   sdk: flutter
  e2e: ^0.2.1
