name: pay_ios
description: A plug-in to add support for payment wallets on the iOS side on Flutter applications.
version: 1.0.0-beta.1
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: TBA

environment:
  sdk: ^2.12.0
  flutter: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PayPlugin

dependencies:
  flutter:
    sdk: flutter
  #pay_platform_interface: ^1.0.0
  pay_platform_interface:
    path: ../pay_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.11.0
  test: ^1.16.5