name: google_pay_mobile
description: A plug-in to add support for Google Pay on Flutter applications.
version: 1.0.0
author: Google Pay Team <payments-devrel@googlegroups.com>
homepage: https://developers.google.com/pay/api/android/overview

environment:
  sdk: ^2.7.0
  flutter: ^1.20.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.google_pay_mobile
        pluginClass: GooglePayPlugin

  assets:
    - assets/

dependencies:
  flutter:
    sdk: flutter
  #google_pay_platform_interface: ^1.0.0
  google_pay_platform_interface:
    path: ../google_pay_platform_interface
  flutter_svg: 0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.6